- name: Install packages from ISO
  hosts: home
  become: true
  gather_facts: false

  vars:
    package_list:
      - net-tools
      - bird
      - lldp
      - openssh-server

  tasks:
    - name: Create /media directory
      file:
        path: /media
        state: directory

    - name: Mount dev/sr0 on /media
      mount:
        src: /dev/sr0
        path: /media
        state: mounted
        fstype: iso9660

    - name: Find all deb packages
      find:
        paths: /media
        patterns: "*.deb"
      register: deb_files

    - name: Dpkg all files
      ignore_errors: true
      apt:
        deb: "{{ item.path }}"
        update_cache: yes
        state: present
        dpkg_options: "--force-confnew"
      with_items: "{{ deb_files.files }}"

    - name: Check if packages are installed
      ignore_errors: true
      shell: dpkg-query -W -f='${Status}' {{ item }} 2>/dev/null | grep -c "ok installed"
      loop: "{{ package_list }}"


